version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/taskdb
      - JWT_SECRET_KEY=change_this_in_production
      - SECRET_KEY=another_secret_key_to_change
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
